updateDataIntervalSeconds: 5
saveUnchangedData: true
deleteAfterDays: 7
files:
  diamond:
    shopName: OreShop
    material: DIAMOND
  gold:
    shopName: OreShop
    material: GOLD_INGOT
graphConfigs:
  diamond30m:
    stockConfig: diamond
    graphLengthMinutes: 30
    graphRefreshTimeSeconds: 10
    type: PRICE
  gold60m:
    stockConfig: gold
    graphLengthMinutes: 60
    graphRefreshTimeSeconds: 10
    type: STOCK