saveUnchangedData: true
deleteAfterDays: 120
webServer: true
port: 8180
customHTML: false
files:
  Diamond:
    shopName: Ore
    material: DIAMOND
  Gold:
    shopName: Ore
    material: GOLD_INGOT
  Iron:
    shopName: Ore
    material: IRON_INGOT
graphConfigs:
  diamond30m:
    stockConfig: Diamond
    graphLengthMinutes: 30
    graphRefreshTimeSeconds: 10
    type: PRICE
  gold60m:
    stockConfig: Gold
    graphLengthMinutes: 60
    graphRefreshTimeSeconds: 10
    type: STOCK