saveUnchangedData: true
deleteAfterDays: 120
webServer: true
port: 8180
customHTML: false
files:
  Diamond:
    shopName: Ore
    material: DIAMOND
  Gold:
    shopName: Ore
    material: GOLD_INGOT
  Iron:
    shopName: Ore
    material: IRON_INGOT
