saveUnchangedData: true
deleteAfterDays: 120
compressAfterHours: 3
webServer: true
port: 8180
customHTML: false
files:
  Diamond:
    shopName: Ore
    material: DIAMOND
  Iron:
    shopName: Ore
    material: IRON_INGOT
